export default {
	terribleColors: [
		{ id: 1, hex: "#ff0000", name: "racecar red" },
		{ id: 2, hex: "#0000ff", name: "water blue" },
		{ id: 3, hex: "#008000", name: "tree green" },
		{ id: 4, hex: "#ffff00", name: "sunshine yellow" },
		{ id: 5, hex: "#ffa500", name: "orangejuice orange" },
		{ id: 6, hex: "#8b4513", name: "stick brown" },
		{ id: 7, hex: "#f6f9de", name: "bread white" },
		{ id: 8, hex: "#1a2920", name: "kettle black" },
		{ id: 9, hex: "#5D00EF", name: "exciting purple" },
		{ id: 10, hex: "#F5F7F3", name: "milk white" },
		{ id: 11, hex: "#f7c3cc", name: "melon pink" },
		{ id: 12, hex: "#62948f", name: "rad turquoise" },
		{ id: 13, hex: "#a1c7a1", name: "good cucumber" },
		{ id: 14, hex: "#d2b48c", name: "tan beach" },
		{ id: 15, hex: "#fff8dc", name: "artistic cornsilk" },
		{ id: 16, hex: "#de8113", name: "seminal bisque" },
		{ id: 17, hex: "#a52a2a", name: "rock star fudge" },
		{ id: 18, hex: "#c19494", name: "fruit pink" }
	],
	terribleWords: [
		{ id: 1, text: "bad" },
		{ id: 2, text: "terrible" },
		{ id: 3, text: "offensive" },
		{ id: 4, text: "severe" },
		{ id: 5, text: "lurid" },
		{ id: 6, text: "obscene" },
		{ id: 7, text: "foul" },
		{ id: 8, text: "immoral" },
		{ id: 9, text: "debauched" },
		{ id: 10, text: "blasphemous" },
		{ id: 10, text: "regrettable" },
		{ id: 11, text: "anxious" },
		{ id: 12, text: "sweaty" },
		{ id: 13, text: "negative" },
		{ id: 14, text: "crusty" },
		{ id: 15, text: "neglegent" },
		{ id: 16, text: "debased" },
		{ id: 17, text: "fleshy" },
		{ id: 18, text: "garbage" },
		{ id: 19, text: "dumpster-fire" },
		{ id: 20, text: "reprehensible" },
		{ id: 21, text: "moist" },
		{ id: 22, text: "steaming" },
		{ id: 23, text: "shameful" }
	],
	terriblePeople: [
		{ id: 1, text: "humans" },
		{ id: 2, text: "souls" },
		{ id: 3, text: "degenerates" },
		{ id: 4, text: "people" },
		{ id: 5, text: "earth killers" },
		{ id: 6, text: "mortals" }
	]
};
